version: '3.0'
services:
  mysql8:
    image: mysql:8.0
    container_name: mysql_server_8
    restart: always
    command:
      # 保持原有的兼容性配置
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 1. 脚本初始化
      - ./script/mysql:/docker-entrypoint-initdb.d/
      # 2. 数据持久化
      - ./mysql_data:/var/lib/mysql
    ports:
      # 端口映射到13316
      - "13316:3306"

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6378:6379"
