apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webook-live-ingress
spec:
  ingressClassName: nginx
  rules:
#    - 当host是 live.webook.com 的时候，命中这条
    - host: live.webook.com
      http:
        paths:
#          - 请求路径的前缀是 / 的时候
#          - 将流量转发过去后面的 webook-live 服务上
#          - 端口是80
          - backend:
              service:
                name: webook-live-srv
                port:
                  number: 81
            pathType: Prefix
            path: /