apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-live-dpm     # 唯一身份证号
spec:
  replicas: 1           # 副本数量
  selector:             # 筛选器，根据标签/名牌，寻找 POD 进行管理
    matchLabels:
      app: webook-live
# POD 模板
  template:             # template 描述的是你的 POD 是什么样的
    metadata:
      labels:
        app: webook-live  # POD 的标签/名牌
    spec:                 # POD的具体信息
      containers:
        - name: webook
          image: gufan/webook:v0.0.1
          ports:
            - containerPort: 8080

