apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  storageClassName:  manual
  capacity:
    storage: 1Gi
  accessModes:  # 声明底层存储具体支持哪些读写模式。
    - ReadWriteOnce
  hostPath: # 宿主机上的物理路径
    path: "/mnt/host/e/projects/go/mount/gin-learning/mysql"